export const BUG_ROUNDS = [
  {
    id: 1,
    language: "javascript",
    lines: [
      "function sum(a, b) {",
      "  return a + b",
      "}",
      "",
      "console.log(sum(2, 3));",
    ],
    buggyLine: 1,
    explanation: "2-qatorda nuqta-vergul (;) yo'q. JavaScript'da buni qo'shish yaxshi amaliyot hisoblanadi.",
  },
  {
    id: 2,
    language: "javascript",
    lines: [
      "const users = [\"Ali\", \"Vali\", \"Guli\"];",
      "",
      "for (let i = 0; i <= users.length; i++) {",
      "  console.log(users[i]);",
      "}",
    ],
    buggyLine: 2,
    explanation: "i <= users.length shartida oxirgi qadamda users[3] (undefined) chaqiriladi. To'g'ri shart: i < users.length.",
  },
  {
    id: 3,
    language: "css",
    lines: [
      ".card {",
      "  display: flex;",
      "  justify-content: center;",
      "  align-item: center;",
      "}",
    ],
    buggyLine: 3,
    explanation: "Xususiyat nomi noto'g'ri yozilgan: align-item emas, align-items bo'lishi kerak.",
  },
  {
    id: 4,
    language: "javascript",
    lines: [
      "function isEven(num) {",
      "  if (num % 2 = 0) {",
      "    return true;",
      "  }",
      "  return false;",
      "}",
    ],
    buggyLine: 1,
    explanation: "Solishtirish uchun = emas, === (yoki ==) ishlatilishi kerak. Bitta = qiymat berish (assignment) belgisi.",
  },
  {
    id: 5,
    language: "python",
    lines: [
      "def greet(name):",
      "    print(\"Salom, \" + name)",
      "",
      "greet(\"Aziz\")",
      "greet(\"Vali\"",
    ],
    buggyLine: 4,
    explanation: "5-qatorda yopuvchi qavs ) yetishmayapti — funksiya chaqiruvi to'liq emas.",
  },
  {
    id: 6,
    language: "javascript",
    lines: [
      "const price = 100;",
      "const discount = 0.2;",
      "",
      "function getFinalPrice() {",
      "  return price - pric * discount;",
      "}",
    ],
    buggyLine: 4,
    explanation: "5-qatorda o'zgaruvchi noto'g'ri yozilgan: pric emas, price bo'lishi kerak.",
  },
];
