import {
  Bug,
  Puzzle,
  Keyboard,
  Brain,
  Blocks,
  Code2,
  LayoutGrid,
  Binary,
  Search,
  MousePointerClick,
  GitBranch,
} from "lucide-react";

export const GAMES = [
  {
    id: "bug-hunter",
    title: "Bug Hunter",
    description: "Kod parchasidagi xatoni toping va koinlar yuting.",
    icon: Bug,
    color: "#EF4444",
    status: "ready",
  },
  {
    id: "syntax-match",
    title: "Syntax Match",
    description: "Sintaksis atamalarini ta'riflari bilan moslashtiring.",
    icon: Puzzle,
    color: "#6366F1",
    status: "ready",
  },
  {
    id: "typing-speed",
    title: "Typing Speed",
    description: "Kodni belgilangan vaqtda tez va aniq tering.",
    icon: Keyboard,
    color: "#22C55E",
    status: "ready",
  },
  { id: "code-memory", title: "Code Memory", description: "Kod bloklarini juftlikda eslab qoling.", icon: Brain, color: "#F5A623", status: "ready" },
  { id: "variable-puzzle", title: "Variable Puzzle", description: "O'zgaruvchilar bilan mantiqiy jumboq yeching.", icon: Blocks, color: "#A855F7", status: "ready" },
  { id: "js-challenge", title: "JavaScript Challenge", description: "JS kod chiqishini bashorat qiling.", icon: Code2, color: "#EAB308", status: "ready" },
  { id: "react-challenge", title: "React Challenge", description: "Komponent xatolarini toping va tuzating.", icon: LayoutGrid, color: "#38BDF8", status: "ready" },
  { id: "function-builder", title: "Function Builder", description: "Bloklardan to'g'ri funksiya tuzing.", icon: Binary, color: "#EC4899", status: "ready" },
  { id: "flexbox-game", title: "CSS Flexbox Game", description: "Flexbox xususiyatlari bilan layout yig'ing.", icon: LayoutGrid, color: "#0EA5E9", status: "ready" },
  { id: "grid-game", title: "Grid Game", description: "CSS Grid bilan panjara qurishni mashq qiling.", icon: Blocks, color: "#14B8A6", status: "ready" },
  { id: "algorithm-game", title: "Algorithm Game", description: "Algoritm qadamlarini to'g'ri tartiblang.", icon: GitBranch, color: "#F97316", status: "ready" },
  { id: "error-finder", title: "Error Finder", description: "Konsol xatolarini tezkor aniqlang.", icon: Search, color: "#EF4444", status: "ready" },
  { id: "drag-drop-coding", title: "Drag & Drop Coding", description: "Kod bloklarini sudrab to'g'ri tartiblang.", icon: MousePointerClick, color: "#6366F1", status: "ready" },
];
