import {
  Smartphone,
  Laptop,
  Headphones,
  Watch,
  Keyboard,
  Mouse,
  Monitor,
  Armchair,
  Mic,
  Camera,
  HardDrive,
  BatteryCharging,
  Usb,
  Tablet,
  Ticket,
  Crown,
} from "lucide-react";

export const PRODUCTS = [
  { id: "phone", name: "Smartfon", description: "Zamonaviy flagman smartfon, o'yin va ishlash uchun.", icon: Smartphone, coin: 12000, stock: 5, color: "#6366F1", image: "/products/phone.jpg" },
  { id: "laptop", name: "Noutbuk", description: "Dasturlash va dizayn uchun kuchli noutbuk.", icon: Laptop, coin: 25000, stock: 3, color: "#3B82F6", image: "/products/laptop.jpg" },
  { id: "headphones", name: "Simsiz naushnik", description: "Shovqinni bostiruvchi premium naushnik.", icon: Headphones, coin: 3200, stock: 12, color: "#EC4899", image: "/products/headphones.jpg" },
  { id: "smartwatch", name: "Smart soat", description: "Sog'liq va bildirishnomalarni kuzatuvchi soat.", icon: Watch, coin: 4500, stock: 8, color: "#22C55E", image: "/products/smartwatch.jpg" },
  { id: "keyboard", name: "Mexanik klaviatura", description: "Dasturchilar sevib ishlatadigan taktil klaviatura.", icon: Keyboard, coin: 1800, stock: 15, color: "#F5A623", image: "/products/keyboard.jpg" },
  { id: "mouse", name: "Gaming sichqoncha", description: "Yuqori aniqlikdagi sensorli sichqoncha.", icon: Mouse, coin: 900, stock: 20, color: "#A855F7", image: "/products/mouse.jpg" },
  { id: "monitor", name: "Monitor", description: "27\" 2K rezolyutsiyali ish monitori.", icon: Monitor, coin: 8500, stock: 6, color: "#0EA5E9", image: "/products/monitor.jpg" },
  { id: "chair", name: "Gaming kreslo", description: "Uzoq soat qulay o'tirish uchun ergonomik kreslo.", icon: Armchair, coin: 9500, stock: 4, color: "#EF4444", image: "/products/chair.jpg" },
  { id: "mic", name: "Mikrofon", description: "Podkast va striming uchun studiya mikrofoni.", icon: Mic, coin: 2600, stock: 10, color: "#F97316", image: "/products/mic.jpg" },
  { id: "webcam", name: "Web kamera", description: "Full HD videokonferensiya kamerasi.", icon: Camera, coin: 1500, stock: 14, color: "#14B8A6", image: "/products/webcam.jpg" },
  { id: "ssd", name: "SSD disk (1TB)", description: "Tezkor NVMe SSD, loyihalaringiz uchun joy.", icon: HardDrive, coin: 2200, stock: 18, color: "#64748B", image: "/products/ssd.jpg" },
  { id: "powerbank", name: "Power Bank", description: "20000mAh quvvatli kuchli quvvat manbai.", icon: BatteryCharging, coin: 750, stock: 25, color: "#22C55E", image: "/products/powerbank.jpg" },
  { id: "usb", name: "USB Flash (128GB)", description: "Tezkor ma'lumot tashish uchun flash disk.", icon: Usb, coin: 400, stock: 30, color: "#6366F1", image: "/products/usb.jpg" },
  { id: "tablet", name: "Planshet", description: "Chizish va o'qish uchun qulay planshet.", icon: Tablet, coin: 9800, stock: 5, color: "#EAB308", image: "/products/tablet.jpg" },
  { id: "coupon", name: "Kurs kuponi (50% chegirma)", description: "Istalgan premium kursga 50% chegirma kuponi.", icon: Ticket, coin: 600, stock: 50, color: "#EC4899", image: "/products/coupon.jpg" },
  { id: "premium", name: "Premium a'zolik (1 oy)", description: "Barcha kurslarga cheklovsiz kirish, reklamasiz interfeys.", icon: Crown, coin: 1200, stock: 40, color: "#F5A623", image: "/products/premium.jpg" },
];
